<?php

namespace Database\Seeders;

use App\Models\Invoice;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Bulk data for local/staging performance testing. Not registered in DatabaseSeeder.
 *
 * Usage:
 *   STRESS_PRODUCTS=20000 STRESS_CUSTOMERS=2000 STRESS_INVOICES=5000 php artisan db:seed --class=StressDataSeeder
 *
 * Defaults (if env omitted): products 10000, customers 1000, invoices 2000.
 * Optional: STRESS_CHUNK=500 (insert batch size), STRESS_LINES_MAX=5 (invoice lines per invoice).
 *
 * On production, set STRESS_SEED_OK=1 or the command aborts.
 *
 * Cleanup (run in order; deleting invoices cascades to invoice_items):
 *   DELETE FROM invoices WHERE invoice_number LIKE 'INV-STRESS-%';
 *   DELETE FROM customers WHERE notes = '__stress_seed__';
 *   DELETE FROM products WHERE sku LIKE 'STRESS-P-%';
 *   DELETE FROM categories WHERE name = 'Stress test catalog';
 *
 * Re-running this seeder without cleanup will fail on duplicate product SKUs.
 */
class StressDataSeeder extends Seeder
{
    private const CUSTOMER_MARKER = '__stress_seed__';

    public function run()
    {
        if (app()->environment('production') && ! filter_var(env('STRESS_SEED_OK', false), FILTER_VALIDATE_BOOLEAN)) {
            $this->command->error('Stress seeding is blocked in production. Set STRESS_SEED_OK=true in .env if you really intend this.');

            return;
        }

        $productTarget = max(0, (int) env('STRESS_PRODUCTS', 10000));
        $customerTarget = max(0, (int) env('STRESS_CUSTOMERS', 1000));
        $invoiceTarget = max(0, (int) env('STRESS_INVOICES', 2000));
        $chunk = max(50, min(2000, (int) env('STRESS_CHUNK', 500)));
        $linesMax = max(1, min(20, (int) env('STRESS_LINES_MAX', 5)));

        $this->command->info(sprintf(
            'Stress seed: products=%d customers=%d invoices=%d chunk=%d',
            $productTarget,
            $customerTarget,
            $invoiceTarget,
            $chunk
        ));

        $now = now()->toDateTimeString();

        $categoryId = DB::table('categories')->where('name', 'Stress test catalog')->value('id');
        if (! $categoryId) {
            $categoryId = DB::table('categories')->insertGetId([
                'name' => 'Stress test catalog',
                'description' => 'Generated by StressDataSeeder',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $this->seedProducts($categoryId, $productTarget, $chunk, $now);
        $this->seedCustomers($customerTarget, $chunk, $now);

        $productBounds = $this->idBoundsLike('products', 'sku', 'STRESS-P-%');
        $customerBounds = $this->idBoundsExact('customers', 'notes', self::CUSTOMER_MARKER);

        if ($invoiceTarget > 0 && $productBounds && $customerBounds) {
            $this->seedInvoices(
                $invoiceTarget,
                $chunk,
                $linesMax,
                $now,
                (int) $productBounds->min_id,
                (int) $productBounds->max_id,
                (int) $customerBounds->min_id,
                (int) $customerBounds->max_id
            );
        } elseif ($invoiceTarget > 0) {
            $this->command->warn('Skipping invoices: need at least one stress product and one stress customer.');
        }

        $this->command->info('Stress seed finished.');
    }

    private function seedProducts(int $categoryId, int $target, int $chunk, string $now): void
    {
        $buffer = [];
        for ($i = 1; $i <= $target; $i++) {
            $buffer[] = [
                'name' => 'Stress product '.$i,
                'sku' => 'STRESS-P-'.$i,
                'category_id' => $categoryId,
                'description' => null,
                'wholesale_price' => 10,
                'retail_price' => 20,
                'purchase_price' => 5,
                'stock_quantity' => 100,
                'minimum_stock_alert' => 1,
                'image_path' => null,
                'barcode' => null,
                'status' => Product::STATUS_ACTIVE,
                'created_at' => $now,
                'updated_at' => $now,
            ];
            if (count($buffer) >= $chunk) {
                DB::table('products')->insert($buffer);
                $buffer = [];
            }
        }
        if ($buffer !== []) {
            DB::table('products')->insert($buffer);
        }
    }

    private function seedCustomers(int $target, int $chunk, string $now): void
    {
        $buffer = [];
        for ($i = 1; $i <= $target; $i++) {
            $buffer[] = [
                'name' => 'Stress customer '.$i,
                'phone' => '090'.str_pad((string) ($i % 10000000), 7, '0', STR_PAD_LEFT),
                'address' => null,
                'notes' => self::CUSTOMER_MARKER,
                'total_debt' => 0,
                'created_at' => $now,
                'updated_at' => $now,
            ];
            if (count($buffer) >= $chunk) {
                DB::table('customers')->insert($buffer);
                $buffer = [];
            }
        }
        if ($buffer !== []) {
            DB::table('customers')->insert($buffer);
        }
    }

    private function idBoundsLike(string $table, string $column, string $pattern): ?object
    {
        $row = DB::table($table)
            ->where($column, 'like', $pattern)
            ->selectRaw('MIN(id) as min_id, MAX(id) as max_id')
            ->first();

        if (! $row || $row->min_id === null || $row->max_id === null) {
            return null;
        }

        return $row;
    }

    private function idBoundsExact(string $table, string $column, string $value): ?object
    {
        $row = DB::table($table)
            ->where($column, '=', $value)
            ->selectRaw('MIN(id) as min_id, MAX(id) as max_id')
            ->first();

        if (! $row || $row->min_id === null || $row->max_id === null) {
            return null;
        }

        return $row;
    }

    private function seedInvoices(
        int $target,
        int $chunk,
        int $linesMax,
        string $now,
        int $productMinId,
        int $productMaxId,
        int $customerMinId,
        int $customerMaxId
    ): void {
        $prefix = 'INV-STRESS-'.substr(str_replace('.', '', (string) microtime(true)), 0, 14).'-';

        for ($n = 1; $n <= $target; $n++) {
            $customerId = mt_rand($customerMinId, $customerMaxId);
            $lineCount = mt_rand(1, $linesMax);

            $lines = [];
            $subtotal = 0.0;
            for ($l = 0; $l < $lineCount; $l++) {
                $productId = mt_rand($productMinId, $productMaxId);
                $qty = mt_rand(1, 5);
                $unit = (float) mt_rand(5, 500);
                $cost = round($unit * 0.5, 2);
                $lineTotal = round($qty * $unit, 2);
                $subtotal += $lineTotal;
                $lines[] = [
                    'product_id' => $productId,
                    'quantity' => $qty,
                    'unit_price' => $unit,
                    'unit_cost' => $cost,
                    'line_total' => $lineTotal,
                ];
            }

            $subtotal = round($subtotal, 2);
            $total = $subtotal;
            $paid = $total;

            $invoiceId = DB::table('invoices')->insertGetId([
                'invoice_number' => $prefix.$n,
                'customer_id' => $customerId,
                'pricing_type' => Invoice::PRICING_RETAIL,
                'subtotal' => $subtotal,
                'discount_amount' => 0,
                'tax_rate' => null,
                'tax_amount' => 0,
                'total' => $total,
                'paid_amount' => $paid,
                'remaining_amount' => 0,
                'payment_status' => Invoice::STATUS_PAID,
                'notes' => null,
                'created_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ]);

            $itemRows = [];
            foreach ($lines as $line) {
                $itemRows[] = [
                    'invoice_id' => $invoiceId,
                    'product_id' => $line['product_id'],
                    'quantity' => $line['quantity'],
                    'unit_price' => $line['unit_price'],
                    'unit_cost' => $line['unit_cost'],
                    'line_total' => $line['line_total'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            }
            foreach (array_chunk($itemRows, $chunk) as $batch) {
                DB::table('invoice_items')->insert($batch);
            }

            if ($n % $chunk === 0) {
                $this->command->info('Invoices created: '.$n.' / '.$target);
            }
        }
    }
}
